name: AWS Cli for Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  cd:
    runs-on: ubuntu-latest
    name: CD
    steps:
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -t ${{ secrets.REGISTRY_USERNAME }}/aws-cli-ci:latest .
          docker push ${{ secrets.REGISTRY_USERNAME }}/aws-cli-ci:latest