name: AWS Cli for Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  cd:
    runs-on: ubuntu-latest
    name: CD
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: JuanDavidGutierrezC/aws-cli-ci
          tag_with_ref: true
          tag_with_sha: true